services:
  delivery-dev-postgresql:
    image: postgres
    volumes:
      - delivery_dev_db:/var/lib/postgresql
      - delivery_dev_data:/var/lib/postgresql/data
    networks:
      - back
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - delivery-dev-postgresql
    networks:
      - back
  hazelcast:
    image: hazelcast/hazelcast
    environment:
      HZ_NETWORK_PUBLICADDRESS : localhost:5701
      HZ_CLUSTERNAME: delivery
    ports:
      - 5701:5701

volumes:
  delivery_dev_data:
  delivery_dev_db:

networks:
  back:
