spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include:
        - env
        - health
        - metrics
        - httpTrace
        - mappings
        - info
        - loggers
        - caches
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      cache: true


---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      connection-timeout: 2000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

